export const DEFAULT_SAVINGS_BANK_COLOR = '#64748B'

export const bankColorMap: Record<string, string> = {
  // 시중은행
  경남은행: '#E60012',
  광주은행: '#005BAC',
  국민은행: '#FFCD00',
  농협은행주식회사: '#00A650',
  부산은행: '#E60012',
  수협은행: '#0072BC',
  신한은행: '#0046FF',
  아이엠뱅크: '#0072CE',
  우리은행: '#0F6EBF',
  전북은행: '#00A3E0',
  제주은행: '#0046FF',
  '주식회사 카카오뱅크': '#FAE100',
  '주식회사 케이뱅크': '#3B82F6',
  '주식회사 하나은행': '#00903F',
  중소기업은행: '#005BAC',
  '토스뱅크 주식회사': '#4B7BEC',
  한국산업은행: '#003478',
  한국스탠다드차타드은행: '#007A33',

  // 저축은행 - 대표색 확인 가능
  BNK저축은행: '#E60012',
  IBK저축은행: '#005BAC',
  JT저축은행: '#E6007E',
  JT친애저축은행: '#E6007E',
  KB저축은행: '#FFCD00',
  OK저축은행: '#F15A24',
  SBI저축은행: '#E60012',
  다올저축은행: '#1E4D8C',
  대신저축은행: '#003C7D',
  디비저축은행: '#0072CE',
  상상인저축은행: '#7A3DB8',
  상상인플러스저축은행: '#8B5CF6',
  신한저축은행: '#0046FF',
  애큐온저축은행: '#00A3E0',
  엔에이치저축은행: '#00A650',
  우리금융저축은행: '#0F6EBF',
  우리저축은행: '#0F6EBF',
  웰컴저축은행: '#00A0E9',
  유안타저축은행: '#E60012',
  키움예스저축은행: '#6B2C91',
  키움저축은행: '#6B2C91',
  페퍼저축은행: '#D71920',
  푸른저축은행: '#009688',
  하나저축은행: '#00903F',
  한국투자저축은행: '#003C7D',
  한화저축은행: '#F37321',
  흥국저축은행: '#E6007E',

  // 저축은행 - 대표색 미확인
  CK저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  DH저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  HB저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  MS저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  OSB저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  고려저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  국제저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  금화저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  남양저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  대명상호저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  대백저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  대아상호저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  대원저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  대한저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  더블저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  더케이저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  동양저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  동원제일저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  드림저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  라온저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  머스트삼일저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  모아저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  민국저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  바로저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  부림저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  삼정저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  삼호저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  세람저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  센트럴저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  솔브레인저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  스마트저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  스카이저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  스타저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  아산저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  안국저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  안양저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  에스앤티저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  영진저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  예가람저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  오성저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  오투저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  유니온저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  융창저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  인성저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  인천저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  조은저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  조흥저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  진주저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  참저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  청주저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  평택저축은행: DEFAULT_SAVINGS_BANK_COLOR,
  한성저축은행: DEFAULT_SAVINGS_BANK_COLOR,
}
