# Generated by Django 5.2.14 on 2026-06-22 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_searchprofile_deposit_amount'),
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('thumbnail_url', models.URLField()),
                ('channel_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_favorites', to='accounts.member')),
            ],
            options={
                'db_table': 'video_favorite',
                'unique_together': {('member', 'video_id')},
            },
        ),
    ]
