# Generated by Django 5.2.14 on 2026-06-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='id',
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
