# Generated by Django 5.2.14 on 2026-06-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_remove_goal_id_goal_goal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='goal_id',
        ),
        migrations.AddField(
            model_name='goal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
