# Generated by Django 5.2.14 on 2026-06-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_remove_goal_goal_id_goal_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
