# Generated by Django 5.2.14 on 2026-05-31 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_amount', models.IntegerField()),
                ('term_months', models.IntegerField()),
                ('expected_payout_at_maturity', models.BigIntegerField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('transfer_day', models.IntegerField()),
                ('enrolled_at', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.member')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='enrollments', to='products.product')),
            ],
            options={
                'db_table': 'enrollment',
                'unique_together': {('member', 'product')},
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('PAID', '납입'), ('MISSED', '미납'), ('PARTIAL', '부분납입')], max_length=10)),
                ('is_modified', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='enrollments.enrollment')),
            ],
            options={
                'db_table': 'payment_record',
                'unique_together': {('enrollment', 'scheduled_date')},
            },
        ),
    ]
