# Generated by Django 5.2.14 on 2026-06-20 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='calculated_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='enrolled_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='expected_payout_at_maturity',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='term_months',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='transfer_day',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='monthly_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentRecord',
        ),
    ]
