# Generated by Django 5.2.14 on 2026-06-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_remove_enrollment_calculated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='deposit_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
