# Generated by Django 5.2.14 on 2026-05-31 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_type', models.CharField(choices=[('FIRST_TIER', '시중은행'), ('SAVINGS', '저축은행')], max_length=20)),
            ],
            options={
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('join_member', models.CharField(blank=True, max_length=500)),
                ('join_way', models.CharField(blank=True, max_length=200)),
                ('max_limit', models.BigIntegerField(blank=True, null=True)),
                ('maturity_interest', models.TextField(blank=True)),
                ('etc_note', models.TextField(blank=True)),
                ('special_condition_raw', models.TextField(blank=True)),
                ('has_bonus', models.BooleanField(default=False)),
                ('maturity_summary', models.TextField(blank=True, null=True)),
                ('join_summary', models.TextField(blank=True, null=True)),
                ('etc_summary', models.TextField(blank=True, null=True)),
                ('dcls_strt_day', models.CharField(blank=True, max_length=8)),
                ('dcls_end_day', models.CharField(blank=True, max_length=8, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='products.bank')),
            ],
            options={
                'db_table': 'product',
                'unique_together': {('bank', 'fin_prdt_cd')},
            },
        ),
        migrations.CreateModel(
            name='PreferentialCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500)),
                ('friendly_label', models.CharField(blank=True, max_length=500, null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('LOW', '쉬움'), ('MID', '보통'), ('HIGH', '어려움')], max_length=4, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='products.product')),
            ],
            options={
                'db_table': 'preferential_condition',
                'unique_together': {('product', 'label')},
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_term', models.IntegerField()),
                ('intr_rate_type', models.CharField(choices=[('S', '단리'), ('M', '복리')], max_length=1)),
                ('rsrv_type', models.CharField(choices=[('S', '정액'), ('F', '자유')], max_length=1)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.product')),
            ],
            options={
                'db_table': 'product_option',
                'unique_together': {('product', 'save_term', 'intr_rate_type', 'rsrv_type')},
            },
        ),
    ]
