# Generated by Django 5.2.14 on 2026-06-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_summary_label_high_product_summary_label_low_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='etc_summary',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_bonus',
        ),
        migrations.RemoveField(
            model_name='product',
            name='join_summary',
        ),
        migrations.RemoveField(
            model_name='product',
            name='maturity_summary',
        ),
        migrations.RemoveField(
            model_name='product',
            name='summary_label_high',
        ),
        migrations.RemoveField(
            model_name='product',
            name='summary_label_low',
        ),
        migrations.RemoveField(
            model_name='product',
            name='summary_label_mid',
        ),
        migrations.AddField(
            model_name='product',
            name='age_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='age_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_auto_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_card_usage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_housing_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_salary_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PreferentialCondition',
        ),
    ]
