# Generated by Django 5.2.14 on 2026-06-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_etc_summary_remove_product_has_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('SAVINGS', '적금'), ('DEPOSIT', '예금')], default='SAVINGS', max_length=20),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='rsrv_type',
            field=models.CharField(blank=True, choices=[('S', '정액'), ('F', '자유')], max_length=1, null=True),
        ),
    ]
