# Generated by Django 5.2.14 on 2026-06-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_product_type_alter_productoption_rsrv_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_limit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_first_transaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_online_signup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_redeposit',
            field=models.BooleanField(default=False),
        ),
    ]
