# Generated by Django 5.2.14 on 2026-05-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('job_status', models.CharField(choices=[('STUDENT', '학생'), ('EMPLOYED', '직장인'), ('OTHER', '기타')], max_length=10)),
                ('marital_status', models.CharField(choices=[('SINGLE', '미혼'), ('MARRIED', '기혼')], max_length=10)),
                ('total_goal_amount', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
