# Generated by Django 5.2.14 on 2026-06-20 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='job_status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='total_goal_amount',
        ),
        migrations.CreateModel(
            name='SearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_term', models.IntegerField(choices=[(3, '3개월'), (6, '6개월'), (12, '12개월'), (24, '24개월'), (36, '36개월')])),
                ('monthly_amount', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('salary_transfer', models.BooleanField()),
                ('auto_transfer', models.BooleanField()),
                ('card_usage', models.BooleanField()),
                ('housing_subscription', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_profile', to='accounts.member')),
            ],
            options={
                'db_table': 'search_profile',
            },
        ),
    ]
