# Generated by Django 5.2.14 on 2026-06-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_member_birth_date_remove_member_job_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprofile',
            name='deposit_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
