# Generated by Django 5.2.14 on 2026-06-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_searchprofile_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprofile',
            name='first_transaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='online_signup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='redeposit',
            field=models.BooleanField(default=False),
        ),
    ]
