# Generated by Django 5.2.14 on 2026-08-23 11:28

from django.db import migrations, models


def backfill_deposit_term(apps, schema_editor):
    # 분리 전에는 예금도 save_term을 썼으므로, 예치금액이 있는 프로필은 같은 기간으로 채운다.
    SearchProfile = apps.get_model("accounts", "SearchProfile")
    for p in SearchProfile.objects.filter(deposit_amount__isnull=False, deposit_term__isnull=True):
        p.deposit_term = p.save_term
        p.save(update_fields=["deposit_term"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_searchprofile_first_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprofile',
            name='deposit_term',
            field=models.IntegerField(blank=True, choices=[(3, '3개월'), (6, '6개월'), (12, '12개월'), (24, '24개월'), (36, '36개월')], null=True),
        ),
        migrations.AlterField(
            model_name='searchprofile',
            name='auto_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='searchprofile',
            name='card_usage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='searchprofile',
            name='housing_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='searchprofile',
            name='monthly_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchprofile',
            name='salary_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='searchprofile',
            name='save_term',
            field=models.IntegerField(blank=True, choices=[(3, '3개월'), (6, '6개월'), (12, '12개월'), (24, '24개월'), (36, '36개월')], null=True),
        ),
            migrations.RunPython(backfill_deposit_term, migrations.RunPython.noop),
    ]
