"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 3rd party
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "drf_spectacular",
    # apps
    "apps.accounts",
    "apps.products",
    "apps.goals",
    "apps.enrollments",
    "apps.favorites",
    "apps.community",
    "apps.videos",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "apps.accounts.authentication.MemberJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "COERCE_DECIMAL_TO_STRING": False,
    # drf-spectacular가 OpenAPI 스키마를 생성하도록 스키마 클래스 지정
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# drf-spectacular (Swagger/OpenAPI 문서)
SPECTACULAR_SETTINGS = {
    "TITLE": "OURWISH API",
    "DESCRIPTION": "사회초년생을 위한 적금과 예금 추천·관리 서비스 백엔드 API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,  # /schema/ 응답에 메타 스키마 항목 숨김
}

# JWT
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

# CORS — 브라우저(프론트)에서 API를 부를 수 있는 출처 목록
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vue 개발 서버
    "https://our-wish.site",  # 운영 프론트(Vercel)
    "https://www.our-wish.site",
]

# nginx가 HTTPS를 종료하고 gunicorn엔 HTTP로 넘기므로, 프록시가 붙이는
# X-Forwarded-Proto 헤더로 "원래 요청은 HTTPS였다"를 Django가 인식하게 한다.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# CSRF — HTTPS 도메인에서의 admin 로그인 등 폼 요청 신뢰 출처
CSRF_TRUSTED_ORIGINS = [
    "https://api.our-wish.site",
]

# 외부 서비스
FSS_API_KEY = os.environ.get("FSS_API_KEY")

# GMS LLM (OpenAI 호환 프록시) — Django가 직접 호출
GMS_API_KEY = os.environ.get("GMS_KEY")
GMS_API_URL = os.environ.get(
    "GMS_API_URL", "https://gms.ssafy.io/gmsapi/api.openai.com/v1/chat/completions"
)
GMS_MODEL = os.environ.get("GMS_MODEL", "gpt-5-mini")

# YouTube Data API v3 — 영상 검색/상세 프록시용. 키는 서버에만 둔다.
YOUTUBE_API_KEY = os.environ.get("YOUTUBE_API_KEY")

# 한국은행 ECOS — STEP1 평균 금리(예금은행 수신금리) 조회용. 키는 서버에만 둔다.
ECOS_API_KEY = os.environ.get("ECOS_API_KEY")
